/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.despesapessoal.view;

/**
 *
 * @author julia
 */
public class GUIDespesaPessoal extends javax.swing.JFrame {

    /**
     * Creates new form GUIDespesaPessoal
     */
    public GUIDespesaPessoal() {
        initComponents();
        
        jDesktopPaneUsuario.setVisible(false);
        jInternalFrameCadastroUsuario.setVisible(false);
        jInternalFrameVisualizarUsuario.setVisible(false);
        jDesktopPaneContas.setVisible(false);
        jInternalFrameCadastroConta.setVisible(false);
        jInternalFrameVisualizarConta.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jDesktopPaneUsuario = new javax.swing.JDesktopPane();
        jInternalFrameCadastroUsuario = new javax.swing.JInternalFrame();
        jLabelCadastroNome = new javax.swing.JLabel();
        jTextFieldCadastroNome = new javax.swing.JTextField();
        jLabelCadastroCPF = new javax.swing.JLabel();
        jFormattedTextFieldCadastroCPF = new javax.swing.JFormattedTextField();
        jLabelCadastroDtNascimento = new javax.swing.JLabel();
        jFormattedTextFieldCadastroDtNascimento = new javax.swing.JFormattedTextField();
        jLabelCadastroGenero = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jLabelCadastroEmail = new javax.swing.JLabel();
        jTextFieldCadastroEmail = new javax.swing.JTextField();
        jLabelCadastroCEP = new javax.swing.JLabel();
        jFormattedTextFieldCadastroCEP = new javax.swing.JFormattedTextField();
        jLabelCadastroEndereco = new javax.swing.JLabel();
        jTextFieldCadastroEndereco = new javax.swing.JTextField();
        jLabelCadastroCidade = new javax.swing.JLabel();
        jTextFieldCadastroCidade = new javax.swing.JTextField();
        jLabelCadastroEstado = new javax.swing.JLabel();
        jTextFieldCadastroEstado = new javax.swing.JTextField();
        jButtonCadastroCancelar = new javax.swing.JButton();
        jButtonCadastroSalvar = new javax.swing.JButton();
        jInternalFrameVisualizarUsuario = new javax.swing.JInternalFrame();
        jLabelCVisualizarNome2 = new javax.swing.JLabel();
        jTextFieldVisualizarNome2 = new javax.swing.JTextField();
        jLabelVisualizarCPF2 = new javax.swing.JLabel();
        jFormattedTextFieldVisualizarCPF2 = new javax.swing.JFormattedTextField();
        jLabelVisualizarDtNascimento2 = new javax.swing.JLabel();
        jFormattedTextFieldVisualizarDtNascimento2 = new javax.swing.JFormattedTextField();
        jLabelVisualizarGenero2 = new javax.swing.JLabel();
        jFormattedTextFieldVisualizarDtNascimento3 = new javax.swing.JFormattedTextField();
        jLabelVisualizarEmail2 = new javax.swing.JLabel();
        jTextFieldVisualizarEmail2 = new javax.swing.JTextField();
        jLabelVisualizarCEP2 = new javax.swing.JLabel();
        jFormattedTextFieldVisualizarCEP2 = new javax.swing.JFormattedTextField();
        jLabelVisualizarEndereco2 = new javax.swing.JLabel();
        jTextFieldVisualizarEndereco2 = new javax.swing.JTextField();
        jLabelVisualizarCidade2 = new javax.swing.JLabel();
        jTextFieldVisualizarCidade2 = new javax.swing.JTextField();
        jLabelVisualizarEstado2 = new javax.swing.JLabel();
        jTextFieldVisualizarEstado2 = new javax.swing.JTextField();
        jButtonCadastroCancelar2 = new javax.swing.JButton();
        jButtonCadastroSalvar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPaneContas = new javax.swing.JDesktopPane();
        jInternalFrameCadastroConta = new javax.swing.JInternalFrame();
        jLabelDescricaoConta = new javax.swing.JLabel();
        jTextFieldDescricaoConta = new javax.swing.JTextField();
        jLabelValorConta = new javax.swing.JLabel();
        jTextFieldValorConta = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jFormattedTextFieldDataConta = new javax.swing.JFormattedTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCalcelar = new javax.swing.JButton();
        jInternalFrameVisualizarConta = new javax.swing.JInternalFrame();
        jLabelVisualizarConta = new javax.swing.JLabel();
        jTextFieldVisualizarConta = new javax.swing.JTextField();
        jLabelVisualizarValorConta = new javax.swing.JLabel();
        jTextFieldVisualizarValorConta = new javax.swing.JTextField();
        jLabelVisualizarData = new javax.swing.JLabel();
        jFormattedTextFieldVisualizarDataConta = new javax.swing.JFormattedTextField();
        jButtonSalvar1 = new javax.swing.JButton();
        jButtonCalcelar1 = new javax.swing.JButton();
        jScrollPaneTabelaContas = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBarMenuPrincipal = new javax.swing.JMenuBar();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemVisualizarUsuarios = new javax.swing.JMenuItem();
        jMenuCadastroUsuario = new javax.swing.JMenu();
        jMenuItemCadastrarUsuario = new javax.swing.JMenuItem();
        jMenuGenero = new javax.swing.JMenu();
        jMenuItemCadastrarGenero = new javax.swing.JMenuItem();
        jMenuItemVisualizarGeneros = new javax.swing.JMenuItem();
        jMenuContas = new javax.swing.JMenu();
        jMenuItemVisualizarContas = new javax.swing.JMenuItem();
        jMenuConta = new javax.swing.JMenu();
        jMenuItemCadastrarConta = new javax.swing.JMenuItem();
        jMenuTipoConta = new javax.swing.JMenu();
        jMenuItemCadastrarTipoConta = new javax.swing.JMenuItem();
        jMenuItemVisualizarTipoConta = new javax.swing.JMenuItem();
        jMenuRendas = new javax.swing.JMenu();
        jMenuItemVisualizarRendas = new javax.swing.JMenuItem();
        jMenuTipoRenda = new javax.swing.JMenu();
        jMenuItemCadastrarRenda = new javax.swing.JMenuItem();
        jMenuItemVisualizarRenda = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanelPrincipal.setLayout(null);

        jDesktopPaneUsuario.setToolTipText("");
        jDesktopPaneUsuario.setAutoscrolls(true);
        jDesktopPaneUsuario.setMaximumSize(new java.awt.Dimension(1200, 700));
        jDesktopPaneUsuario.setName(""); // NOI18N

        jInternalFrameCadastroUsuario.setClosable(true);
        jInternalFrameCadastroUsuario.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameCadastroUsuario.setIconifiable(true);
        jInternalFrameCadastroUsuario.setResizable(true);
        jInternalFrameCadastroUsuario.setTitle("Cadastro de Usuário");
        jInternalFrameCadastroUsuario.setToolTipText("");
        jInternalFrameCadastroUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrameCadastroUsuario.setName(""); // NOI18N
        jInternalFrameCadastroUsuario.setVisible(true);

        jLabelCadastroNome.setText("Nome:");

        jLabelCadastroCPF.setText("CPF:");

        try {
            jFormattedTextFieldCadastroCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelCadastroDtNascimento.setText("Data Nascimento:");

        jFormattedTextFieldCadastroDtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabelCadastroGenero.setText("Sexo:");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));
        jComboBoxGenero.setSelectedIndex(-1);

        jLabelCadastroEmail.setText("E-mail:");

        jLabelCadastroCEP.setText("CEP:");

        try {
            jFormattedTextFieldCadastroCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelCadastroEndereco.setText("Endereço:");

        jLabelCadastroCidade.setText("Cidade:");

        jLabelCadastroEstado.setText("Estado:");

        jButtonCadastroCancelar.setText("Cancelar");
        jButtonCadastroCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCancelarActionPerformed(evt);
            }
        });

        jButtonCadastroSalvar.setText("Salvar");
        jButtonCadastroSalvar.setPreferredSize(new java.awt.Dimension(78, 28));
        jButtonCadastroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastroUsuarioLayout = new javax.swing.GroupLayout(jInternalFrameCadastroUsuario.getContentPane());
        jInternalFrameCadastroUsuario.getContentPane().setLayout(jInternalFrameCadastroUsuarioLayout);
        jInternalFrameCadastroUsuarioLayout.setHorizontalGroup(
            jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastroUsuarioLayout.createSequentialGroup()
                        .addComponent(jButtonCadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadastroCancelar)
                        .addGap(27, 27, 27))
                    .addGroup(jInternalFrameCadastroUsuarioLayout.createSequentialGroup()
                        .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelCadastroCEP)
                                .addComponent(jLabelCadastroNome)
                                .addComponent(jTextFieldCadastroNome)
                                .addComponent(jTextFieldCadastroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCadastroEndereco)
                                .addGroup(jInternalFrameCadastroUsuarioLayout.createSequentialGroup()
                                    .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCadastroCidade)
                                        .addComponent(jTextFieldCadastroCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)
                                    .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jInternalFrameCadastroUsuarioLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jTextFieldCadastroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelCadastroEstado)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameCadastroUsuarioLayout.createSequentialGroup()
                                    .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCadastroCPF)
                                        .addComponent(jFormattedTextFieldCadastroCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCadastroEmail))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jFormattedTextFieldCadastroDtNascimento)
                                        .addComponent(jComboBoxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jInternalFrameCadastroUsuarioLayout.createSequentialGroup()
                                            .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelCadastroGenero)
                                                .addComponent(jLabelCadastroDtNascimento))
                                            .addGap(176, 176, 176)))))
                            .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldCadastroEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldCadastroCEP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                        .addContainerGap(80, Short.MAX_VALUE))))
        );
        jInternalFrameCadastroUsuarioLayout.setVerticalGroup(
            jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabelCadastroNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastroCPF)
                    .addComponent(jLabelCadastroDtNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCadastroDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCadastroCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroEmail)
                    .addComponent(jLabelCadastroGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCadastroCEP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldCadastroCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCadastroEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCadastroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroCidade)
                    .addComponent(jLabelCadastroEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadastroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jInternalFrameCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroCancelar)
                    .addComponent(jButtonCadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jInternalFrameVisualizarUsuario.setClosable(true);
        jInternalFrameVisualizarUsuario.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameVisualizarUsuario.setIconifiable(true);
        jInternalFrameVisualizarUsuario.setResizable(true);
        jInternalFrameVisualizarUsuario.setTitle("Lista de Usuários");
        jInternalFrameVisualizarUsuario.setToolTipText("");
        jInternalFrameVisualizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrameVisualizarUsuario.setName(""); // NOI18N
        jInternalFrameVisualizarUsuario.setVisible(true);

        jLabelCVisualizarNome2.setText("Nome:");

        jLabelVisualizarCPF2.setText("CPF:");

        try {
            jFormattedTextFieldVisualizarCPF2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelVisualizarDtNascimento2.setText("Data Nascimento:");

        jFormattedTextFieldVisualizarDtNascimento2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabelVisualizarGenero2.setText("Sexo:");

        jFormattedTextFieldVisualizarDtNascimento3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabelVisualizarEmail2.setText("E-mail:");

        jLabelVisualizarCEP2.setText("CEP:");

        try {
            jFormattedTextFieldVisualizarCEP2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelVisualizarEndereco2.setText("Endereço:");

        jLabelVisualizarCidade2.setText("Cidade:");

        jLabelVisualizarEstado2.setText("Estado:");

        jButtonCadastroCancelar2.setText("Fechar");
        jButtonCadastroCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCancelar2ActionPerformed(evt);
            }
        });

        jButtonCadastroSalvar2.setText("Editar");
        jButtonCadastroSalvar2.setPreferredSize(new java.awt.Dimension(78, 28));

        jScrollPane1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "E-mail", "CPF", "Dt. Nascimento", "Sexo", "CEP", "Endereço", "Cidade", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jInternalFrameVisualizarUsuarioLayout = new javax.swing.GroupLayout(jInternalFrameVisualizarUsuario.getContentPane());
        jInternalFrameVisualizarUsuario.getContentPane().setLayout(jInternalFrameVisualizarUsuarioLayout);
        jInternalFrameVisualizarUsuarioLayout.setHorizontalGroup(
            jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameVisualizarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameVisualizarUsuarioLayout.createSequentialGroup()
                        .addGroup(jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrameVisualizarUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabelVisualizarCidade2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVisualizarCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(jLabelVisualizarEstado2))
                            .addComponent(jLabelVisualizarEndereco2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVisualizarEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193)
                        .addComponent(jButtonCadastroSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastroCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jInternalFrameVisualizarUsuarioLayout.createSequentialGroup()
                            .addComponent(jLabelVisualizarCEP2)
                            .addGap(18, 18, 18)
                            .addComponent(jFormattedTextFieldVisualizarCEP2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(159, 159, 159)
                            .addComponent(jTextFieldVisualizarEndereco2)
                            .addGap(10, 10, 10))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameVisualizarUsuarioLayout.createSequentialGroup()
                            .addGroup(jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrameVisualizarUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabelCVisualizarNome2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldVisualizarNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jInternalFrameVisualizarUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabelVisualizarCPF2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jFormattedTextFieldVisualizarCPF2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelVisualizarDtNascimento2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jFormattedTextFieldVisualizarDtNascimento2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(39, 39, 39)
                            .addGroup(jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelVisualizarGenero2)
                                .addComponent(jLabelVisualizarEmail2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldVisualizarDtNascimento3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldVisualizarEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jInternalFrameVisualizarUsuarioLayout.setVerticalGroup(
            jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameVisualizarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCVisualizarNome2)
                    .addComponent(jTextFieldVisualizarNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVisualizarEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisualizarEmail2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVisualizarCPF2)
                    .addComponent(jFormattedTextFieldVisualizarCPF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisualizarDtNascimento2)
                    .addComponent(jFormattedTextFieldVisualizarDtNascimento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisualizarGenero2)
                    .addComponent(jFormattedTextFieldVisualizarDtNascimento3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldVisualizarCEP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisualizarCEP2)
                    .addComponent(jLabelVisualizarEndereco2)
                    .addComponent(jTextFieldVisualizarEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameVisualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVisualizarCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisualizarCidade2)
                    .addComponent(jLabelVisualizarEstado2)
                    .addComponent(jTextFieldVisualizarEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastroSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastroCancelar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPaneUsuario.setLayer(jInternalFrameCadastroUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneUsuario.setLayer(jInternalFrameVisualizarUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneUsuarioLayout = new javax.swing.GroupLayout(jDesktopPaneUsuario);
        jDesktopPaneUsuario.setLayout(jDesktopPaneUsuarioLayout);
        jDesktopPaneUsuarioLayout.setHorizontalGroup(
            jDesktopPaneUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrameVisualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrameCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPaneUsuarioLayout.setVerticalGroup(
            jDesktopPaneUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPaneUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrameVisualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrameCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jDesktopPaneUsuario);
        jDesktopPaneUsuario.setBounds(0, 0, 1200, 700);

        jDesktopPaneContas.setToolTipText("");
        jDesktopPaneContas.setAutoscrolls(true);
        jDesktopPaneContas.setMaximumSize(new java.awt.Dimension(1200, 700));
        jDesktopPaneContas.setName(""); // NOI18N

        jInternalFrameCadastroConta.setClosable(true);
        jInternalFrameCadastroConta.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameCadastroConta.setIconifiable(true);
        jInternalFrameCadastroConta.setResizable(true);
        jInternalFrameCadastroConta.setTitle("Cadastro de Conta");
        jInternalFrameCadastroConta.setToolTipText("");
        jInternalFrameCadastroConta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrameCadastroConta.setMaximumSize(new java.awt.Dimension(600, 400));
        jInternalFrameCadastroConta.setName(""); // NOI18N
        jInternalFrameCadastroConta.setPreferredSize(new java.awt.Dimension(600, 400));
        jInternalFrameCadastroConta.setVisible(true);

        jLabelDescricaoConta.setText("Descrição da Conta:");

        jLabelValorConta.setText("Valor:");

        jTextFieldValorConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorContaActionPerformed(evt);
            }
        });

        jLabelData.setText("Data:");

        try {
            jFormattedTextFieldDataConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonSalvar.setText("Salvar");

        jButtonCalcelar.setText("Cancelar");

        javax.swing.GroupLayout jInternalFrameCadastroContaLayout = new javax.swing.GroupLayout(jInternalFrameCadastroConta.getContentPane());
        jInternalFrameCadastroConta.getContentPane().setLayout(jInternalFrameCadastroContaLayout);
        jInternalFrameCadastroContaLayout.setHorizontalGroup(
            jInternalFrameCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroContaLayout.createSequentialGroup()
                .addGroup(jInternalFrameCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jInternalFrameCadastroContaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCalcelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrameCadastroContaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jInternalFrameCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelData)
                            .addComponent(jLabelValorConta)
                            .addComponent(jLabelDescricaoConta))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrameCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDescricaoConta)
                            .addComponent(jTextFieldValorConta)
                            .addComponent(jFormattedTextFieldDataConta, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jInternalFrameCadastroContaLayout.setVerticalGroup(
            jInternalFrameCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroContaLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jInternalFrameCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescricaoConta)
                    .addComponent(jTextFieldDescricaoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorConta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDataConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData))
                .addGap(52, 52, 52)
                .addGroup(jInternalFrameCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCalcelar))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jInternalFrameVisualizarConta.setClosable(true);
        jInternalFrameVisualizarConta.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrameVisualizarConta.setIconifiable(true);
        jInternalFrameVisualizarConta.setResizable(true);
        jInternalFrameVisualizarConta.setTitle("Visualizar Conta");
        jInternalFrameVisualizarConta.setToolTipText("");
        jInternalFrameVisualizarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrameVisualizarConta.setMaximumSize(new java.awt.Dimension(600, 400));
        jInternalFrameVisualizarConta.setName(""); // NOI18N
        jInternalFrameVisualizarConta.setPreferredSize(new java.awt.Dimension(600, 400));
        jInternalFrameVisualizarConta.setVisible(true);

        jLabelVisualizarConta.setText("Descrição da Conta:");

        jLabelVisualizarValorConta.setText("Valor:");

        jTextFieldVisualizarValorConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVisualizarValorContaActionPerformed(evt);
            }
        });

        jLabelVisualizarData.setText("Data:");

        try {
            jFormattedTextFieldVisualizarDataConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonSalvar1.setText("Salvar");

        jButtonCalcelar1.setText("Cancelar");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descrição", "Valor", "Data Pagamento", "Data Criação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneTabelaContas.setViewportView(jTable2);

        javax.swing.GroupLayout jInternalFrameVisualizarContaLayout = new javax.swing.GroupLayout(jInternalFrameVisualizarConta.getContentPane());
        jInternalFrameVisualizarConta.getContentPane().setLayout(jInternalFrameVisualizarContaLayout);
        jInternalFrameVisualizarContaLayout.setHorizontalGroup(
            jInternalFrameVisualizarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameVisualizarContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameVisualizarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameVisualizarContaLayout.createSequentialGroup()
                        .addGroup(jInternalFrameVisualizarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelVisualizarConta)
                            .addComponent(jLabelVisualizarValorConta)
                            .addComponent(jLabelVisualizarData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrameVisualizarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldVisualizarValorConta, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrameVisualizarContaLayout.createSequentialGroup()
                                .addComponent(jTextFieldVisualizarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButtonSalvar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCalcelar1))
                            .addComponent(jFormattedTextFieldVisualizarDataConta, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jScrollPaneTabelaContas))
                .addContainerGap())
        );
        jInternalFrameVisualizarContaLayout.setVerticalGroup(
            jInternalFrameVisualizarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameVisualizarContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameVisualizarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVisualizarConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisualizarConta)
                    .addComponent(jButtonSalvar1)
                    .addComponent(jButtonCalcelar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameVisualizarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVisualizarValorConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisualizarValorConta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameVisualizarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldVisualizarDataConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisualizarData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTabelaContas, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPaneContas.setLayer(jInternalFrameCadastroConta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneContas.setLayer(jInternalFrameVisualizarConta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneContasLayout = new javax.swing.GroupLayout(jDesktopPaneContas);
        jDesktopPaneContas.setLayout(jDesktopPaneContasLayout);
        jDesktopPaneContasLayout.setHorizontalGroup(
            jDesktopPaneContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneContasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrameCadastroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jDesktopPaneContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPaneContasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFrameVisualizarConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jDesktopPaneContasLayout.setVerticalGroup(
            jDesktopPaneContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneContasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrameCadastroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPaneContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPaneContasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFrameVisualizarConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanelPrincipal.add(jDesktopPaneContas);
        jDesktopPaneContas.setBounds(0, 0, 1200, 700);

        getContentPane().add(jPanelPrincipal);
        jPanelPrincipal.setBounds(0, 0, 1330, 660);

        jMenuUsuarios.setText("Usuários");

        jMenuItemVisualizarUsuarios.setText("Visualizar Usuários");
        jMenuItemVisualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarUsuariosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemVisualizarUsuarios);

        jMenuCadastroUsuario.setText("Cadastrar Usuário");

        jMenuItemCadastrarUsuario.setText("Cadastrar");
        jMenuItemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastroUsuario.add(jMenuItemCadastrarUsuario);

        jMenuUsuarios.add(jMenuCadastroUsuario);

        jMenuGenero.setText("Cadastrar / Visualizar Genero");

        jMenuItemCadastrarGenero.setText("Cadastrar");
        jMenuGenero.add(jMenuItemCadastrarGenero);

        jMenuItemVisualizarGeneros.setText("Visualizar");
        jMenuGenero.add(jMenuItemVisualizarGeneros);

        jMenuUsuarios.add(jMenuGenero);

        jMenuBarMenuPrincipal.add(jMenuUsuarios);

        jMenuContas.setText("Contas");

        jMenuItemVisualizarContas.setText("Visualizar Contas");
        jMenuItemVisualizarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarContasActionPerformed(evt);
            }
        });
        jMenuContas.add(jMenuItemVisualizarContas);

        jMenuConta.setText("Cadastrar Conta ");

        jMenuItemCadastrarConta.setText("Cadastrar");
        jMenuItemCadastrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarContaActionPerformed(evt);
            }
        });
        jMenuConta.add(jMenuItemCadastrarConta);

        jMenuContas.add(jMenuConta);

        jMenuTipoConta.setText("Cadastrar / Visualizar Tipo de Conta ");

        jMenuItemCadastrarTipoConta.setText("Cadastrar");
        jMenuTipoConta.add(jMenuItemCadastrarTipoConta);

        jMenuItemVisualizarTipoConta.setText("Visualizar");
        jMenuTipoConta.add(jMenuItemVisualizarTipoConta);

        jMenuContas.add(jMenuTipoConta);

        jMenuBarMenuPrincipal.add(jMenuContas);

        jMenuRendas.setText("Rendas");

        jMenuItemVisualizarRendas.setText("Visualizar Rendas");
        jMenuRendas.add(jMenuItemVisualizarRendas);

        jMenuTipoRenda.setText("Cadastrar / Visualizar Tipo de Renda");

        jMenuItemCadastrarRenda.setText("Cadastrar");
        jMenuTipoRenda.add(jMenuItemCadastrarRenda);

        jMenuItemVisualizarRenda.setText("Visualizar");
        jMenuTipoRenda.add(jMenuItemVisualizarRenda);

        jMenuRendas.add(jMenuTipoRenda);

        jMenuBarMenuPrincipal.add(jMenuRendas);

        jMenuSair.setText("Sair");
        jMenuBarMenuPrincipal.add(jMenuSair);

        setJMenuBar(jMenuBarMenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        jDesktopPaneUsuario.setVisible(true);
        jInternalFrameCadastroUsuario.setVisible(true);
        jInternalFrameVisualizarUsuario.setVisible(false);
    }//GEN-LAST:event_jMenuItemCadastrarUsuarioActionPerformed

    private void jButtonCadastroCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCancelarActionPerformed
        // TODO add your handling code here:
        jDesktopPaneUsuario.setVisible(false);
        jInternalFrameCadastroUsuario.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroCancelarActionPerformed

    private void jButtonCadastroCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCancelar2ActionPerformed
        // TODO add your handling code here:
        jDesktopPaneUsuario.setVisible(false);
        jInternalFrameVisualizarUsuario.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroCancelar2ActionPerformed

    private void jMenuItemVisualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarUsuariosActionPerformed
        // TODO add your handling code here:
        jDesktopPaneUsuario.setVisible(true);
        jInternalFrameCadastroUsuario.setVisible(false);
        jInternalFrameVisualizarUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemVisualizarUsuariosActionPerformed

    private void jButtonCadastroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroSalvarActionPerformed
        // TODO add your handling code here:
             
                
    }//GEN-LAST:event_jButtonCadastroSalvarActionPerformed

    private void jMenuItemCadastrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarContaActionPerformed
        // TODO add your handling code here:
        jDesktopPaneContas.setVisible(true);
        jInternalFrameCadastroConta.setVisible(true);
        jInternalFrameVisualizarConta.setVisible(false);
    }//GEN-LAST:event_jMenuItemCadastrarContaActionPerformed

    private void jTextFieldValorContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorContaActionPerformed

    private void jTextFieldVisualizarValorContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVisualizarValorContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVisualizarValorContaActionPerformed

    private void jMenuItemVisualizarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarContasActionPerformed
        // TODO add your handling code here:
        jDesktopPaneContas.setVisible(true);
        jInternalFrameVisualizarConta.setVisible(true);
        jInternalFrameCadastroConta.setVisible(false);
    }//GEN-LAST:event_jMenuItemVisualizarContasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDespesaPessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDespesaPessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDespesaPessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDespesaPessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIDespesaPessoal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroCancelar;
    private javax.swing.JButton jButtonCadastroCancelar2;
    private javax.swing.JButton jButtonCadastroSalvar;
    private javax.swing.JButton jButtonCadastroSalvar2;
    private javax.swing.JButton jButtonCalcelar;
    private javax.swing.JButton jButtonCalcelar1;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSalvar1;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JDesktopPane jDesktopPaneContas;
    private javax.swing.JDesktopPane jDesktopPaneUsuario;
    private javax.swing.JFormattedTextField jFormattedTextFieldCadastroCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCadastroCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCadastroDtNascimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataConta;
    private javax.swing.JFormattedTextField jFormattedTextFieldVisualizarCEP2;
    private javax.swing.JFormattedTextField jFormattedTextFieldVisualizarCPF2;
    private javax.swing.JFormattedTextField jFormattedTextFieldVisualizarDataConta;
    private javax.swing.JFormattedTextField jFormattedTextFieldVisualizarDtNascimento2;
    private javax.swing.JFormattedTextField jFormattedTextFieldVisualizarDtNascimento3;
    private javax.swing.JInternalFrame jInternalFrameCadastroConta;
    private javax.swing.JInternalFrame jInternalFrameCadastroUsuario;
    private javax.swing.JInternalFrame jInternalFrameVisualizarConta;
    private javax.swing.JInternalFrame jInternalFrameVisualizarUsuario;
    private javax.swing.JLabel jLabelCVisualizarNome2;
    private javax.swing.JLabel jLabelCadastroCEP;
    private javax.swing.JLabel jLabelCadastroCPF;
    private javax.swing.JLabel jLabelCadastroCidade;
    private javax.swing.JLabel jLabelCadastroDtNascimento;
    private javax.swing.JLabel jLabelCadastroEmail;
    private javax.swing.JLabel jLabelCadastroEndereco;
    private javax.swing.JLabel jLabelCadastroEstado;
    private javax.swing.JLabel jLabelCadastroGenero;
    private javax.swing.JLabel jLabelCadastroNome;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDescricaoConta;
    private javax.swing.JLabel jLabelValorConta;
    private javax.swing.JLabel jLabelVisualizarCEP2;
    private javax.swing.JLabel jLabelVisualizarCPF2;
    private javax.swing.JLabel jLabelVisualizarCidade2;
    private javax.swing.JLabel jLabelVisualizarConta;
    private javax.swing.JLabel jLabelVisualizarData;
    private javax.swing.JLabel jLabelVisualizarDtNascimento2;
    private javax.swing.JLabel jLabelVisualizarEmail2;
    private javax.swing.JLabel jLabelVisualizarEndereco2;
    private javax.swing.JLabel jLabelVisualizarEstado2;
    private javax.swing.JLabel jLabelVisualizarGenero2;
    private javax.swing.JLabel jLabelVisualizarValorConta;
    private javax.swing.JMenuBar jMenuBarMenuPrincipal;
    private javax.swing.JMenu jMenuCadastroUsuario;
    private javax.swing.JMenu jMenuConta;
    private javax.swing.JMenu jMenuContas;
    private javax.swing.JMenu jMenuGenero;
    private javax.swing.JMenuItem jMenuItemCadastrarConta;
    private javax.swing.JMenuItem jMenuItemCadastrarGenero;
    private javax.swing.JMenuItem jMenuItemCadastrarRenda;
    private javax.swing.JMenuItem jMenuItemCadastrarTipoConta;
    private javax.swing.JMenuItem jMenuItemCadastrarUsuario;
    private javax.swing.JMenuItem jMenuItemVisualizarContas;
    private javax.swing.JMenuItem jMenuItemVisualizarGeneros;
    private javax.swing.JMenuItem jMenuItemVisualizarRenda;
    private javax.swing.JMenuItem jMenuItemVisualizarRendas;
    private javax.swing.JMenuItem jMenuItemVisualizarTipoConta;
    private javax.swing.JMenuItem jMenuItemVisualizarUsuarios;
    private javax.swing.JMenu jMenuRendas;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuTipoConta;
    private javax.swing.JMenu jMenuTipoRenda;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneTabelaContas;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldCadastroCidade;
    private javax.swing.JTextField jTextFieldCadastroEmail;
    private javax.swing.JTextField jTextFieldCadastroEndereco;
    private javax.swing.JTextField jTextFieldCadastroEstado;
    private javax.swing.JTextField jTextFieldCadastroNome;
    private javax.swing.JTextField jTextFieldDescricaoConta;
    private javax.swing.JTextField jTextFieldValorConta;
    private javax.swing.JTextField jTextFieldVisualizarCidade2;
    private javax.swing.JTextField jTextFieldVisualizarConta;
    private javax.swing.JTextField jTextFieldVisualizarEmail2;
    private javax.swing.JTextField jTextFieldVisualizarEndereco2;
    private javax.swing.JTextField jTextFieldVisualizarEstado2;
    private javax.swing.JTextField jTextFieldVisualizarNome2;
    private javax.swing.JTextField jTextFieldVisualizarValorConta;
    // End of variables declaration//GEN-END:variables
}
